version: '3'

services:
  api:
    image: matheusslr/viver-bem-api:latest
    container_name: viver-bem-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    expose:
      - 8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/viverbem?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: on-failure
    command: mvn spring-boot:run
    networks:
      - viver-bem-network

  postgres:
    container_name: postgres_container
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - viverbem:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - viver-bem-network

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USERNAME}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - viver-bem-network
    depends_on:
      - postgres

networks:
  viver-bem-network:
    driver: bridge

volumes:
  viverbem: