version: '3'

services:
  api:
    image: matheusslr/viver-bem-api:latest
    container_name: viver-bem-api
    ports:
      - "8080:8080"
    expose:
      - 8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-viver-bem.a.aivencloud.com:11061/defaultdb?sslmode=require&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SECURITY_JWT_TOKEN_SECRET=${SECRET_KEY}
      - SECURITY_JWT_TOKEN_TIME=3600000
      - CORS_ORIGINPATTERNS=http://localhost:3000
    restart: on-failure
    command: mvn spring-boot:run