version: '3'

services:
  postgres:
    container_name: postgres_container
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: viverbem
      POSTGRES_PASSWORD: viverbem
    volumes:
      - viverbem:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - postgres
    depends_on:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  viverbem: