spring:
  config:
    import: file:env.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/viverbem?createDatabaseIfNotExist=true
    username: viverbem
    password: viverbem
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect