CREATE TABLE apartment (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   number_ap BIGINT,
   description VARCHAR(255),
   status VARCHAR(255),
   CONSTRAINT pk_apartment PRIMARY KEY (id)
);

ALTER TABLE apartment ADD CONSTRAINT uc_apartment_number_ap UNIQUE (number_ap);