CREATE TABLE contract (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   start_date date,
   end_date date,
   price DECIMAL,
   description VARCHAR(255),
   CONSTRAINT pk_contract PRIMARY KEY (id)
);

CREATE TABLE contract_apartment (
  apartment_id BIGINT,
   contract_id BIGINT NOT NULL,
   CONSTRAINT pk_contract_apartment PRIMARY KEY (contract_id)
);

ALTER TABLE contract_apartment ADD CONSTRAINT fk_conapa_on_apartment FOREIGN KEY (apartment_id) REFERENCES apartment (id);

ALTER TABLE contract_apartment ADD CONSTRAINT fk_conapa_on_contract FOREIGN KEY (contract_id) REFERENCES contract (id);