CREATE TABLE payment (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   price DECIMAL,
   due_date date,
   payment_date date,
   payment_type VARCHAR(255),
   payment_status VARCHAR(255),
   CONSTRAINT pk_payment PRIMARY KEY (id)
);

CREATE TABLE payment_contract (
   contract_uuid UUID,
   payment_id BIGINT NOT NULL,
   CONSTRAINT pk_payment_contract PRIMARY KEY (payment_id)
);

ALTER TABLE payment_contract ADD CONSTRAINT fk_paycon_on_contract FOREIGN KEY (contract_uuid) REFERENCES contract (uuid);

ALTER TABLE payment_contract ADD CONSTRAINT fk_paycon_on_payment FOREIGN KEY (payment_id) REFERENCES payment (id);