CREATE TABLE tenant (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   cpf VARCHAR(11),
   phone VARCHAR(11),
   rg VARCHAR(9),
   birth_date date,
   birth_state VARCHAR(255),
   CONSTRAINT pk_tenant PRIMARY KEY (id)
);

CREATE TABLE tenant_apartment (
  apartment_id BIGINT,
   tenant_id BIGINT NOT NULL,
   CONSTRAINT pk_tenant_apartment PRIMARY KEY (tenant_id)
);

ALTER TABLE tenant ADD CONSTRAINT uc_tenant_cpf UNIQUE (cpf);

ALTER TABLE tenant ADD CONSTRAINT uc_tenant_rg UNIQUE (rg);

ALTER TABLE tenant_apartment ADD CONSTRAINT fk_tenapa_on_apartment FOREIGN KEY (apartment_id) REFERENCES apartment (id);

ALTER TABLE tenant_apartment ADD CONSTRAINT fk_tenapa_on_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id);