CREATE TABLE tb_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   email VARCHAR(255),
   password VARCHAR(255),
   profile_picture BYTEA,
   is_account_non_expired BOOLEAN,
   is_account_non_locked BOOLEAN,
   is_credentials_non_expired BOOLEAN,
   is_enabled BOOLEAN,
   CONSTRAINT pk_tb_user PRIMARY KEY (id)
);