name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Environment Variables
        run: |
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> $GITHUB_ENV
          echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" >> $GITHUB_ENV
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
          echo "SPRING_CONFIG_IMPORT=optional:file:.env[.properties]" >> $GITHUB_ENV

      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '13'
          postgresql db: viverbem
          postgresql user: ${{ secrets.DB_USERNAME }}
          postgresql password: ${{ secrets.DB_PASSWORD }}

      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Run Maven tests
        run: |
          echo "spring.datasource.url=jdbc:postgresql://localhost:5432/viverbem?createDatabaseIfNotExist=true" >> .env
          echo "spring.datasource.username=${{ secrets.DB_USERNAME }}" >> .env
          echo "spring.datasource.password=${{ secrets.DB_PASSWORD }}" >> .env
          echo "spring.jpa.hibernate.ddl-auto=update" >> .env
          echo "spring.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect" >> .env
          echo "security.jwt.token.secret" >> .env

          mvn test
  
  deploy:
    name: Deploy
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}