name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  postgres:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_USER: ${{ secrets.DB_USERNAME }}
          POSTGRES_DB: viverbem
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

  build:
    runs-on: ubuntu-latest

    needs: postgres

    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Build Application JAR
        run: mvn clean package

      - name: Docker Compose
        run: docker compose build

      - name: Push to Docker Hub Container Registry
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/viver-bem-api:latest ${{ secrets.DOCKER_USERNAME }}/viver-bem-api:${{ github.run_id }}
          docker push ${{ secrets.DOCKER_USERNAME }}/viver-bem-api:${{ github.run_id }}
          docker push ${{ secrets.DOCKER_USERNAME }}/viver-bem-api:latest
