name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Build Application JAR
      run: mvn clean package

    - name: Docker Compose
      run: docker compose build
      
    - name: Push to Docker Hub Container Registry
      run:
          docker tag ${{ secrets.DOCKER_USERNAME }}/viver-bem-api:latest ${{ secrets.DOCKER_USERNAME }}/viver-bem-api:${{ github.run_id }}
           
          docker push ${{ secrets.DOCKER_USERNAME }}/viver-bem-api:${{ github.run_id }}
          
          docker push ${{ secrets.DOCKER_USERNAME }}/viver-bem-api:latest
